### ISSUE TITLE
[0][Easy]LandingPage] Download button + determine OS automatically

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#273]
We should have a download button directly on the navbar. This download button would be able to directly activate downloading depending on the user's OS.

- Need function to determine user's OS automatically.
- Need to test this functionality on multiple browsers to make sure works (chrome, safari, firefox, arc, opera, brave)

**Comment by akash3444** [comment]
Can I take this?

**Comment by akash3444** [comment]
@Fryingpannn, what should the download behavior be for operating systems other than Windows and macOS?

Additionally, if macOS is detected, should we also identify the chip type, or should we display a popup where users can select the relevant chip?

**Comment by Fryingpannn** [comment]
@akash3444 For macOS, we should indeed determine the chip type.

For linux, it should link to a blogs page, which will contain linux info for download (https://github.com/orgs/trypear/projects/9/views/1?pane=issue&itemId=79470745)

**Comment by akash3444** [comment]
Got it! @Fryingpannn what should the download behavior be when the OS is detected as Android, iOS, or something else?

**Comment by akash3444** [comment]
@Fryingpannn 
I ran into some trouble figuring out how to detect the chip type on a user's macOS system. Oddly enough, the user-agent string always says `Intel` even for Macs with Apple Silicon chips.

A better way to get the system architecture is by using `navigator.userAgentData.getHighEntropyValues(['architecture'])`. This method gives you the system’s architecture, where `arm` means it's an Apple Silicon chip, and `x86` or `x86_64` refers to an Intel chip (according to some AI tools—though I couldn’t confirm this since I don’t have an Intel-based Mac to test it on). This is also [not supported](https://caniuse.com/?search=getHighEntropyValues) in browsers such as Firefox, Safari, etc.
